### ISSUE TITLE
Implement supported file format settings and client config

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/metamedia-geonode#4]

**Comment by mattiagiupponi** [comment]
@DavidQuartz can you please provide the actual configuration of the supported format in the client?
So I can keep the same structure that is already used

**Comment by mattiagiupponi** [comment]
https://github.com/GeoNode/geonode/issues/9591

**Comment by mattiagiupponi** [comment]
is included in the issue above, integrated in the @DavidQuartz work
